language: python
sudo: false

before_install:
  - git clone https://github.com/GoogleCloudPlatform/gcloud-python-wheels
        gcloud-python-wheels
  - export WHEELHOUSE="$(pwd)/gcloud-python-wheels/wheelhouse/"

install:
  - scripts/custom_pip_install.sh tox

script:
  - tox -e py26
  - tox -e py27
  - tox -e py34
  - tox -e lint
  - tox -e regression
  - scripts/merge.sh

after_success:
  - tox -e coveralls

deploy:
  provider: pypi
  user: silvolu
  password:
    secure: keSFPLzVj/yAAJ8kw4m+U5kpIiGqubpDqhcHPlGAvMohFMIO4D8ffgCqJdbhQshTtb/wiS5ajK1KNpEzq4BKD/5oRXuj/sIRTMENzX/azUXkT/bADLEGocyfE4/NAGQ9mcDOmHntjt7UUhYN6H87rgex22er4V1vD5tGf5Kc1HU=
  on:
    tags: true
    repo: GoogleCloudPlatform/gcloud-python
    # until this is fixed: https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
