rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: main
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'cla/google'
    - 'docs'
    - 'mypy (3.8)'
    - 'mypy (3.9)'
    - 'mypy (3.10)'
    - 'mypy (3.11)'
    - 'mypy (3.12)'
    - 'mypy (3.13)'
    - 'showcase (3.7, showcase)'
    - 'showcase (3.13, showcase)'
    - 'showcase (3.7, showcase_alternative_templates)'
    - 'showcase (3.13, showcase_alternative_templates)'
    - 'showcase (3.7, showcase_w_rest_async)'
    - 'showcase (3.13, showcase_w_rest_async)'
    # TODO(dovs): reenable these when the mtls tests have been debugged and fixed
    # See #1218 for details
    # - 'showcase-mtls (showcase_mtls)'
    # - 'showcase-mtls (showcase_mtls_alternative_templates)'
    - 'showcase-mypy'
    - 'showcase-mypy (_alternative_templates)'
    - 'showcase-unit (3.7)'
    - 'showcase-unit (3.8)'
    - 'showcase-unit (3.9)'
    - 'showcase-unit (3.10)'
    - 'showcase-unit (3.11)'
    - 'showcase-unit (3.12)'
    - 'showcase-unit (3.13)'
    - 'showcase-unit (3.7, _alternative_templates)'
    - 'showcase-unit (3.8, _alternative_templates)'
    - 'showcase-unit (3.9, _alternative_templates)'
    - 'showcase-unit (3.10, _alternative_templates)'
    - 'showcase-unit (3.11, _alternative_templates)'
    - 'showcase-unit (3.12, _alternative_templates)'
    - 'showcase-unit (3.13, _alternative_templates)'
    - 'showcase-unit (3.7, _alternative_templates_mixins)'
    - 'showcase-unit (3.8, _alternative_templates_mixins)'
    - 'showcase-unit (3.9, _alternative_templates_mixins)'
    - 'showcase-unit (3.10, _alternative_templates_mixins)'
    - 'showcase-unit (3.11, _alternative_templates_mixins)'
    - 'showcase-unit (3.12, _alternative_templates_mixins)'
    - 'showcase-unit (3.13, _alternative_templates_mixins)'
    - 'showcase-unit (3.7, _mixins)'
    - 'showcase-unit (3.8, _mixins)'
    - 'showcase-unit (3.9, _mixins)'
    - 'showcase-unit (3.10, _mixins)'
    - 'showcase-unit (3.11, _mixins)'
    - 'showcase-unit (3.12, _mixins)'
    - 'showcase-unit (3.13, _mixins)'
    - 'showcase-unit (3.7, _w_rest_async)'
    - 'showcase-unit (3.8, _w_rest_async)'
    - 'showcase-unit (3.9, _w_rest_async)'
    - 'showcase-unit (3.10, _w_rest_async)'
    - 'showcase-unit (3.11, _w_rest_async)'
    - 'showcase-unit (3.12, _w_rest_async)'
    - 'showcase-unit (3.13, _w_rest_async)'
    - 'showcase-unit-add-iam-methods'
    - 'integration'
    - 'goldens-lint'
    - 'goldens-prerelease'
    - 'goldens-unit'
    - 'lint'
    - 'snippetgen'
    - 'unit (3.7)'
    - 'unit (3.8)'
    - 'unit (3.9)'
    - 'unit (3.10)'
    - 'unit (3.11)'
    - 'unit (3.12)'
    - 'unit (3.13)'
    - 'fragment (3.7)'
    - 'fragment (3.8)'
    - 'fragment (3.9)'
    - 'fragment (3.10)'
    - 'fragment (3.11)'
    - 'fragment (3.12)'
    - 'fragment (3.13)'
    - 'fragment (3.7, _alternative_templates)'
    - 'fragment (3.8, _alternative_templates)'
    - 'fragment (3.9, _alternative_templates)'
    - 'fragment (3.10, _alternative_templates)'
    - 'fragment (3.11, _alternative_templates)'
    - 'fragment (3.12, _alternative_templates)'
    - 'fragment (3.13, _alternative_templates)'
    - 'OwlBot Post Processor'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: actools
    permission: admin
  - team: yoshi-python
    permission: push
  - team: actools-python
    permission: push
