rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
- pattern: master
  isAdminEnforced: true
  requiredStatusCheckContexts:
    - 'ci/circleci: docs'
    - 'ci/circleci: mypy'
    - 'ci/circleci: showcase'
    - 'ci/circleci: showcase-alternative-templates'
    - 'ci/circleci: showcase-mtls'
    - 'ci/circleci: showcase-mtls-alternative-templates'
    - 'ci/circleci: showcase-mypy'
    - 'ci/circleci: showcase-mypy-alternative-templates'
    - 'ci/circleci: showcase-unit-3.6'
    - 'ci/circleci: showcase-unit-3.7'
    - 'ci/circleci: showcase-unit-3.8'
    - 'ci/circleci: showcase-unit-add-iam-methods'
    - 'ci/circleci: showcase-unit-alternative-templates-3.7'
    - 'ci/circleci: showcase-unit-alternative-templates-3.8'
    - 'ci/circleci: style-check'
    - 'ci/circleci: unit-3.6'
    - 'ci/circleci: unit-3.7'
    - 'ci/circleci: unit-3.8'
    - 'cla/google'
    - 'codecov/patch'
    - 'codecov/project'
    - 'conventionalcommits.org'
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
permissionRules:
  - team: actools
    permission: admin
  - team: yoshi-python
    permission: push
