---
version: 2
workflows:
  version: 2
  tests:
    jobs:
      - unit-3.6
      - unit-3.7
      - docs
jobs:
  unit-3.6:
    docker:
      - image: 'python:3.6'
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install --pre nox-automation
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.6
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  unit-3.7:
    docker:
      - image: 'python:3.7'
    steps:
      - checkout
      - run:
          name: Install nox and codecov.
          command: |
            pip install --pre nox-automation
            pip install codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.7
      - run:
          name: Submit coverage data to codecov.
          command: codecov
          when: always
  docs:
    docker:
      - image: 'python:3.6'
    steps:
      - checkout
      - run:
          name: Install nox.
          command: pip install --pre nox-automation
      - run:
          name: Build the documentation.
          command: nox -s docs
