# https://github.com/googleapis/repo-automation-bots/tree/main/packages/sync-repo-settings
# Rules for main branch protection
branchProtectionRules:
# Identifies the protection rule pattern. Name of the branch to be protected.
# Defaults to `main`
- pattern: main
  requiresCodeOwnerReviews: true
  requiresStrictStatusChecks: true
  requiredStatusCheckContexts:
    - 'cla/google'
    - 'OwlBot Post Processor'
    - 'lint'
    # TODO: Enable once the docs tests ready.
    # - 'docs'
    - 'unit (3.7)'
    - 'unit (3.8)'
    - 'unit (3.11)'
    - 'unit (3.12)'
    - 'cover'
    # TODO: enable once the samples tests ready.
    # - 'Samples - Lint'
    # - 'Samples - Python 3.8'
    # - 'Samples - Python 3.9'
    # - 'Samples - Python 3.10'
    # - 'Samples - Python 3.11'
    # - 'Samples - Python 3.12'
permissionRules:
  - team: actools-python
    permission: admin
  - team: actools
    permission: admin
  - team: api-bigquery
    permission: push
  - team: api-bigquery-dataframe
    permission: push
  - team: yoshi-python
    permission: push
  - team: python-samples-owners
    permission: push
  - team: python-samples-reviewers
    permission: push