global_files_allowlist:
  # Allow the container to read and write the root `CHANGELOG.md`
  # file during the `release` step to update the latest client library
  # versions which are hardcoded in the file.
  - path: "CHANGELOG.md"
    permissions: "read-write"
libraries:
- id: "google-ads-admanager"
  generate_blocked: true
- id: "google-ads-datamanager"
  generate_blocked: true
- id: "google-ads-marketingplatform-admin"
  generate_blocked: true
- id: "google-ai-generativelanguage"
  generate_blocked: true
- id: "google-analytics-admin"
  generate_blocked: true
- id: "google-analytics-data"
  generate_blocked: true
- id: "googleapis-common-protos"
  generate_blocked: true
- id: "google-apps-card"
  generate_blocked: true
- id: "google-apps-chat"
  generate_blocked: true
- id: "google-apps-events-subscriptions"
  generate_blocked: true
- id: "google-apps-meet"
  generate_blocked: true
- id: "google-apps-script-type"
  generate_blocked: true
- id: "google-area120-tables"
  generate_blocked: true
- id: "google-cloud-access-approval"
  generate_blocked: true
- id: "google-cloud-access-context-manager"
  generate_blocked: true
- id: "google-cloud-advisorynotifications"
  generate_blocked: true
- id: "google-cloud-alloydb"
  generate_blocked: true
- id: "google-cloud-alloydb-connectors"
  generate_blocked: true
- id: "google-cloud-api-gateway"
  generate_blocked: true
- id: "google-cloud-apigee-connect"
  generate_blocked: true
- id: "google-cloud-apigee-registry"
  generate_blocked: true
- id: "google-cloud-apihub"
  generate_blocked: true
- id: "google-cloud-api-keys"
  generate_blocked: true
- id: "google-cloud-appengine-admin"
  generate_blocked: true
- id: "google-cloud-appengine-logging"
  generate_blocked: true
- id: "google-cloud-apphub"
  generate_blocked: true
- id: "google-cloud-artifact-registry"
  generate_blocked: true
- id: "google-cloud-asset"
  generate_blocked: true
- id: "google-cloud-assured-workloads"
  generate_blocked: true
- id: "google-cloud-audit-log"
  generate_blocked: true
- id: "google-cloud-automl"
  generate_blocked: true
- id: "google-cloud-backupdr"
  generate_blocked: true
- id: "google-cloud-bare-metal-solution"
  generate_blocked: true
- id: "google-cloud-batch"
  generate_blocked: true
- id: "google-cloud-beyondcorp-appconnections"
  generate_blocked: true
- id: "google-cloud-beyondcorp-appconnectors"
  generate_blocked: true
- id: "google-cloud-beyondcorp-appgateways"
  generate_blocked: true
- id: "google-cloud-beyondcorp-clientconnectorservices"
  generate_blocked: true
- id: "google-cloud-beyondcorp-clientgateways"
  generate_blocked: true
- id: "google-cloud-biglake"
  generate_blocked: true
- id: "google-cloud-bigquery-analyticshub"
  generate_blocked: true
- id: "google-cloud-bigquery-biglake"
  generate_blocked: true
- id: "google-cloud-bigquery-connection"
  generate_blocked: true
- id: "google-cloud-bigquery-data-exchange"
  generate_blocked: true
- id: "google-cloud-bigquery-datapolicies"
  generate_blocked: true
- id: "google-cloud-bigquery-datatransfer"
  generate_blocked: true
- id: "google-cloud-bigquery-logging"
  generate_blocked: true
- id: "google-cloud-bigquery-migration"
  generate_blocked: true
- id: "google-cloud-bigquery-reservation"
  generate_blocked: true
- id: "google-cloud-billing"
  generate_blocked: true
- id: "google-cloud-billing-budgets"
  generate_blocked: true
- id: "google-cloud-binary-authorization"
  generate_blocked: true
- id: "google-cloud-build"
  generate_blocked: true
- id: "google-cloud-capacityplanner"
  generate_blocked: true
- id: "google-cloud-certificate-manager"
  generate_blocked: true
- id: "google-cloud-channel"
  generate_blocked: true
- id: "google-cloud-chronicle"
  generate_blocked: true
- id: "google-cloud-cloudcontrolspartner"
  generate_blocked: true
- id: "google-cloud-cloudsecuritycompliance"
  generate_blocked: true
- id: "google-cloud-commerce-consumer-procurement"
  generate_blocked: true
- id: "google-cloud-common"
  generate_blocked: true
- id: "google-cloud-compute"
  generate_blocked: true
- id: "google-cloud-compute-v1beta"
  generate_blocked: true
- id: "google-cloud-confidentialcomputing"
  generate_blocked: true
- id: "google-cloud-config"
  generate_blocked: true
- id: "google-cloud-configdelivery"
  generate_blocked: true
- id: "google-cloud-contact-center-insights"
  generate_blocked: true
- id: "google-cloud-container"
  generate_blocked: true
- id: "google-cloud-containeranalysis"
  generate_blocked: true
- id: "google-cloud-contentwarehouse"
  generate_blocked: true
- id: "google-cloud-databasecenter"
  generate_blocked: true
- id: "google-cloud-datacatalog"
  generate_blocked: true
- id: "google-cloud-datacatalog-lineage"
  generate_blocked: true
- id: "google-cloud-dataflow-client"
  generate_blocked: true
- id: "google-cloud-dataform"
  generate_blocked: true
- id: "google-cloud-data-fusion"
  generate_blocked: true
- id: "google-cloud-datalabeling"
  generate_blocked: true
- id: "google-cloud-dataplex"
  generate_blocked: true
- id: "google-cloud-dataproc"
  generate_blocked: true
- id: "google-cloud-dataproc-metastore"
  generate_blocked: true
- id: "google-cloud-data-qna"
  generate_blocked: true
- id: "google-cloud-datastream"
  generate_blocked: true
- id: "google-cloud-deploy"
  generate_blocked: true
- id: "google-cloud-developerconnect"
  generate_blocked: true
- id: "google-cloud-devicestreaming"
  generate_blocked: true
- id: "google-cloud-dialogflow"
  generate_blocked: true
- id: "google-cloud-dialogflow-cx"
  generate_blocked: true
- id: "google-cloud-dlp"
  generate_blocked: true
- id: "google-cloud-dms"
  generate_blocked: true
- id: "google-cloud-documentai"
  generate_blocked: true
- id: "google-cloud-domains"
  generate_blocked: true
- id: "google-cloud-edgecontainer"
  generate_blocked: true
- id: "google-cloud-edgenetwork"
  generate_blocked: true
- id: "google-cloud-enterpriseknowledgegraph"
  generate_blocked: true
- id: "google-cloud-essential-contacts"
  generate_blocked: true
- id: "google-cloud-eventarc"
  generate_blocked: true
- id: "google-cloud-eventarc-publishing"
  generate_blocked: true
- id: "google-cloud-filestore"
  generate_blocked: true
- id: "google-cloud-financialservices"
  generate_blocked: true
- id: "google-cloud-functions"
  generate_blocked: true
- id: "google-cloud-gdchardwaremanagement"
  generate_blocked: true
- id: "google-cloud-geminidataanalytics"
  generate_blocked: true
- id: "google-cloud-gke-backup"
  generate_blocked: true
- id: "google-cloud-gke-connect-gateway"
  generate_blocked: true
- id: "google-cloud-gke-hub"
  generate_blocked: true
- id: "google-cloud-gke-multicloud"
  generate_blocked: true
- id: "google-cloud-gkerecommender"
  generate_blocked: true
- id: "google-cloud-gsuiteaddons"
  generate_blocked: true
- id: "google-cloud-hypercomputecluster"
  generate_blocked: true
- id: "google-cloud-iam"
  generate_blocked: true
- id: "google-cloud-iam-logging"
  generate_blocked: true
- id: "google-cloud-iap"
  generate_blocked: true
- id: "google-cloud-ids"
  generate_blocked: true
- id: "google-cloud-kms"
  generate_blocked: true
- id: "google-cloud-kms-inventory"
  generate_blocked: true
- id: "google-cloud-language"
  generate_blocked: true
- id: "google-cloud-licensemanager"
  generate_blocked: true
- id: "google-cloud-life-sciences"
  generate_blocked: true
- id: "google-cloud-locationfinder"
  generate_blocked: true
- id: "google-cloud-lustre"
  generate_blocked: true
- id: "google-cloud-maintenance-api"
  generate_blocked: true
- id: "google-cloud-managed-identities"
  generate_blocked: true
- id: "google-cloud-managedkafka"
  generate_blocked: true
- id: "google-cloud-managedkafka-schemaregistry"
  generate_blocked: true
- id: "google-cloud-media-translation"
  generate_blocked: true
- id: "google-cloud-memcache"
  generate_blocked: true
- id: "google-cloud-memorystore"
  generate_blocked: true
- id: "google-cloud-migrationcenter"
  generate_blocked: true
- id: "google-cloud-modelarmor"
  generate_blocked: true
- id: "google-cloud-monitoring"
  generate_blocked: true
- id: "google-cloud-monitoring-dashboards"
  generate_blocked: true
- id: "google-cloud-monitoring-metrics-scopes"
  generate_blocked: true
- id: "google-cloud-netapp"
  generate_blocked: true
- id: "google-cloud-network-connectivity"
  generate_blocked: true
- id: "google-cloud-network-management"
  generate_blocked: true
- id: "google-cloud-network-security"
  generate_blocked: true
- id: "google-cloud-network-services"
  generate_blocked: true
- id: "google-cloud-notebooks"
  generate_blocked: true
- id: "google-cloud-optimization"
  generate_blocked: true
- id: "google-cloud-oracledatabase"
  generate_blocked: true
- id: "google-cloud-orchestration-airflow"
  generate_blocked: true
- id: "google-cloud-org-policy"
  generate_blocked: true
- id: "google-cloud-os-config"
  generate_blocked: true
- id: "google-cloud-os-login"
  generate_blocked: true
- id: "google-cloud-parallelstore"
  generate_blocked: true
- id: "google-cloud-parametermanager"
  generate_blocked: true
- id: "google-cloud-phishing-protection"
  generate_blocked: true
- id: "google-cloud-policysimulator"
  generate_blocked: true
- id: "google-cloud-policy-troubleshooter"
  generate_blocked: true
- id: "google-cloud-policytroubleshooter-iam"
  generate_blocked: true
- id: "google-cloud-private-ca"
  generate_blocked: true
- id: "google-cloud-private-catalog"
  generate_blocked: true
- id: "google-cloud-privilegedaccessmanager"
  generate_blocked: true
- id: "google-cloud-quotas"
  generate_blocked: true
- id: "google-cloud-rapidmigrationassessment"
  generate_blocked: true
- id: "google-cloud-recaptcha-enterprise"
  generate_blocked: true
- id: "google-cloud-recommendations-ai"
  generate_blocked: true
- id: "google-cloud-recommender"
  generate_blocked: true
- id: "google-cloud-redis"
  generate_blocked: true
- id: "google-cloud-redis-cluster"
  generate_blocked: true
- id: "google-cloud-resource-manager"
  generate_blocked: true
- id: "google-cloud-retail"
  generate_blocked: true
- id: "google-cloud-run"
  generate_blocked: true
- id: "google-cloud-saasplatform-saasservicemgmt"
  generate_blocked: true
- id: "google-cloud-scheduler"
  generate_blocked: true
- id: "google-cloud-securesourcemanager"
  generate_blocked: true
- id: "google-cloud-securitycenter"
  generate_blocked: true
- id: "google-cloud-securitycentermanagement"
  generate_blocked: true
- id: "google-cloud-security-publicca"
  generate_blocked: true
- id: "google-cloud-service-control"
  generate_blocked: true
- id: "google-cloud-service-directory"
  generate_blocked: true
- id: "google-cloud-servicehealth"
  generate_blocked: true
- id: "google-cloud-service-management"
  generate_blocked: true
- id: "google-cloud-service-usage"
  generate_blocked: true
- id: "google-cloud-shell"
  generate_blocked: true
- id: "google-cloud-source-context"
  generate_blocked: true
- id: "google-cloud-storagebatchoperations"
  generate_blocked: true
- id: "google-cloud-storage-control"
  generate_blocked: true
- id: "google-cloud-storageinsights"
  generate_blocked: true
- id: "google-cloud-storage-transfer"
  generate_blocked: true
- id: "google-cloud-support"
  generate_blocked: true
- id: "google-cloud-talent"
  generate_blocked: true
- id: "google-cloud-tasks"
  generate_blocked: true
- id: "google-cloud-telcoautomation"
  generate_blocked: true
- id: "google-cloud-texttospeech"
  generate_blocked: true
- id: "google-cloud-tpu"
  generate_blocked: true
- id: "google-cloud-trace"
  generate_blocked: true
- id: "google-cloud-translate"
  generate_blocked: true
- id: "google-cloud-vectorsearch"
  generate_blocked: true
- id: "google-cloud-videointelligence"
  generate_blocked: true
- id: "google-cloud-video-live-stream"
  generate_blocked: true
- id: "google-cloud-video-stitcher"
  generate_blocked: true
- id: "google-cloud-video-transcoder"
  generate_blocked: true
- id: "google-cloud-vision"
  generate_blocked: true
- id: "google-cloud-visionai"
  generate_blocked: true
- id: "google-cloud-vm-migration"
  generate_blocked: true
- id: "google-cloud-vmwareengine"
  generate_blocked: true
- id: "google-cloud-vpc-access"
  generate_blocked: true
- id: "google-cloud-webrisk"
  generate_blocked: true
- id: "google-cloud-websecurityscanner"
  generate_blocked: true
- id: "google-cloud-workflows"
  generate_blocked: true
- id: "google-cloud-workstations"
  generate_blocked: true
- id: "google-geo-type"
  generate_blocked: true
- id: "google-maps-addressvalidation"
  generate_blocked: true
- id: "google-maps-areainsights"
  generate_blocked: true
- id: "google-maps-fleetengine"
  generate_blocked: true
- id: "google-maps-fleetengine-delivery"
  generate_blocked: true
- id: "google-maps-mapsplatformdatasets"
  generate_blocked: true
- id: "google-maps-places"
  generate_blocked: true
- id: "google-maps-routeoptimization"
  generate_blocked: true
- id: "google-maps-routing"
  generate_blocked: true
- id: "google-maps-solar"
  generate_blocked: true
- id: "google-shopping-css"
  generate_blocked: true
- id: "google-shopping-merchant-accounts"
  generate_blocked: true
- id: "google-shopping-merchant-conversions"
  generate_blocked: true
- id: "google-shopping-merchant-datasources"
  generate_blocked: true
- id: "google-shopping-merchant-inventories"
  generate_blocked: true
- id: "google-shopping-merchant-issueresolution"
  generate_blocked: true
- id: "google-shopping-merchant-lfp"
  generate_blocked: true
- id: "google-shopping-merchant-notifications"
  generate_blocked: true
- id: "google-shopping-merchant-ordertracking"
  generate_blocked: true
- id: "google-shopping-merchant-products"
  generate_blocked: true
- id: "google-shopping-merchant-productstudio"
  generate_blocked: true
- id: "google-shopping-merchant-promotions"
  generate_blocked: true
- id: "google-shopping-merchant-quota"
  generate_blocked: true
- id: "google-shopping-merchant-reports"
  generate_blocked: true
- id: "google-shopping-merchant-reviews"
  generate_blocked: true
- id: "google-shopping-type"
  generate_blocked: true
- id: "grafeas"
  generate_blocked: true
- id: "grpc-google-iam-v1"
  generate_blocked: true